-- Optional tables for direct message persistence.
-- The provider will still work without these tables if SAVE_MESSAGES=false.

create table if not exists public.whatsapp_messages (
  id bigint generated by default as identity primary key,
  business_id text not null,
  session_id text,
  message_id text,
  direction text not null,
  phone_number text,
  message_text text,
  created_at timestamptz default now()
);

create index if not exists whatsapp_messages_business_id_idx
  on public.whatsapp_messages (business_id);

create index if not exists whatsapp_messages_phone_idx
  on public.whatsapp_messages (phone_number);

-- This is intentionally minimal because existing Sodah customers
-- table schemas may differ. The provider's customer upsert is optional.
